//go:build (!go1.17 || (go1.17 && !go1.18 && !goexperiment.regabireflect) || (go1.18 && !go1.19 && !goexperiment.regabireflect && !amd64) || (go1.19 && !go1.20 && !goexperiment.regabiargs && !amd64 && !arm64 && !ppc64 && !ppc64le) || (go1.20 && !goexperiment.regabiargs && !amd64 && !arm64 && !ppc64 && !ppc64le && !riscv64)) && (!js || (js && wasm))
// +build !go1.17 go1.17,!go1.18,!goexperiment.regabireflect go1.18,!go1.19,!goexperiment.regabireflect,!amd64 go1.19,!go1.20,!goexperiment.regabiargs,!amd64,!arm64,!ppc64,!ppc64le go1.20,!goexperiment.regabiargs,!amd64,!arm64,!ppc64,!ppc64le,!riscv64
// +build !js js,wasm

package icall

import (
	"reflect"
	"unsafe"

	"github.com/goplus/reflectx/abi"
)

const capacity = 512

type provider struct {
	used map[int]*abi.MethodInfo
}

func (p *provider) Insert(info *abi.MethodInfo) (ifn unsafe.Pointer, index int) {
	for i := 0; i < capacity; i++ {
		if _, ok := p.used[i]; !ok {
			p.used[i] = info
			fn := icall_array[i]
			return unsafe.Pointer(reflect.ValueOf(fn).Pointer()), i
		}
	}
	return nil, -1
}

func (p *provider) Available() int {
	return capacity - len(p.used)
}

func (p *provider) Remove(indexs []int) {
	for _, n := range indexs {
		delete(p.used, n)
	}
}

func (p *provider) Used() int {
	return len(p.used)
}

func (p *provider) Cap() int {
	return len(icall_array)
}

func (p *provider) Clear() {
	p.used = make(map[int]*reflectx.MethodInfo)
}

var (
	mp = &provider{
		used: make(map[int]*reflectx.MethodInfo),
	}
)

func init() {
	abi.AddMethodProvider(mp)
}

func i_x(index int, ptr unsafe.Pointer, p unsafe.Pointer) {
	info := mp.used[index]
	var receiver reflect.Value
	if !info.Pointer && info.OnePtr {
		receiver = reflect.NewAt(info.Type, unsafe.Pointer(&ptr)).Elem()
	} else {
		receiver = reflect.NewAt(info.Type, ptr)
		if !info.Pointer || info.Indirect {
			receiver = receiver.Elem()
		}
	}
	in := []reflect.Value{receiver}
	if inCount := info.Func.Type().NumIn(); inCount > 1 {
		sz := info.InTyp.Size()
		buf := make([]byte, sz, sz)
		if sz > info.InSize {
			sz = info.InSize
		}
		for i := uintptr(0); i < sz; i++ {
			buf[i] = *(*byte)(add(p, i, ""))
		}
		var inArgs reflect.Value
		if sz == 0 {
			inArgs = reflect.New(info.InTyp).Elem()
		} else {
			inArgs = reflect.NewAt(info.InTyp, unsafe.Pointer(&buf[0])).Elem()
		}
		for i := 1; i < inCount; i++ {
			in = append(in, inArgs.Field(i-1))
		}
	}
	var r []reflect.Value
	if info.Variadic {
		r = info.Func.CallSlice(in)
	} else {
		r = info.Func.Call(in)
	}
	if info.OutTyp.NumField() > 0 {
		out := reflect.New(info.OutTyp).Elem()
		for i, v := range r {
			out.Field(i).Set(v)
		}
		po := unsafe.Pointer(out.UnsafeAddr())
		for i := uintptr(0); i < info.OutSize; i++ {
			*(*byte)(add(p, info.InSize+i, "")) = *(*byte)(add(po, uintptr(i), ""))
		}
	}
}

func add(p unsafe.Pointer, x uintptr, whySafe string) unsafe.Pointer {
	return unsafe.Pointer(uintptr(p) + x)
}

type unsafeptr = unsafe.Pointer

var icall_array = []interface{}{
	func(p, a unsafeptr) { i_x(0, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(1, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(2, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(3, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(4, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(5, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(6, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(7, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(8, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(9, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(10, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(11, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(12, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(13, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(14, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(15, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(16, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(17, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(18, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(19, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(20, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(21, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(22, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(23, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(24, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(25, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(26, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(27, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(28, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(29, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(30, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(31, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(32, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(33, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(34, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(35, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(36, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(37, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(38, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(39, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(40, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(41, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(42, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(43, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(44, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(45, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(46, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(47, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(48, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(49, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(50, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(51, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(52, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(53, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(54, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(55, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(56, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(57, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(58, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(59, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(60, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(61, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(62, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(63, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(64, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(65, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(66, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(67, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(68, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(69, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(70, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(71, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(72, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(73, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(74, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(75, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(76, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(77, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(78, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(79, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(80, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(81, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(82, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(83, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(84, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(85, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(86, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(87, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(88, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(89, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(90, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(91, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(92, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(93, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(94, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(95, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(96, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(97, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(98, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(99, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(100, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(101, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(102, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(103, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(104, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(105, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(106, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(107, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(108, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(109, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(110, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(111, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(112, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(113, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(114, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(115, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(116, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(117, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(118, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(119, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(120, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(121, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(122, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(123, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(124, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(125, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(126, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(127, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(128, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(129, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(130, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(131, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(132, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(133, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(134, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(135, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(136, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(137, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(138, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(139, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(140, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(141, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(142, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(143, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(144, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(145, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(146, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(147, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(148, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(149, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(150, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(151, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(152, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(153, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(154, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(155, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(156, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(157, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(158, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(159, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(160, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(161, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(162, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(163, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(164, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(165, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(166, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(167, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(168, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(169, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(170, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(171, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(172, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(173, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(174, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(175, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(176, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(177, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(178, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(179, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(180, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(181, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(182, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(183, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(184, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(185, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(186, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(187, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(188, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(189, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(190, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(191, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(192, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(193, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(194, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(195, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(196, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(197, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(198, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(199, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(200, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(201, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(202, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(203, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(204, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(205, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(206, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(207, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(208, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(209, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(210, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(211, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(212, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(213, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(214, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(215, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(216, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(217, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(218, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(219, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(220, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(221, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(222, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(223, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(224, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(225, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(226, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(227, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(228, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(229, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(230, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(231, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(232, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(233, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(234, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(235, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(236, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(237, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(238, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(239, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(240, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(241, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(242, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(243, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(244, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(245, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(246, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(247, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(248, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(249, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(250, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(251, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(252, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(253, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(254, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(255, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(256, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(257, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(258, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(259, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(260, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(261, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(262, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(263, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(264, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(265, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(266, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(267, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(268, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(269, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(270, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(271, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(272, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(273, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(274, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(275, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(276, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(277, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(278, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(279, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(280, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(281, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(282, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(283, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(284, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(285, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(286, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(287, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(288, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(289, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(290, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(291, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(292, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(293, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(294, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(295, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(296, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(297, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(298, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(299, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(300, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(301, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(302, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(303, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(304, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(305, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(306, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(307, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(308, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(309, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(310, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(311, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(312, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(313, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(314, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(315, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(316, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(317, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(318, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(319, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(320, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(321, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(322, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(323, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(324, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(325, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(326, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(327, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(328, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(329, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(330, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(331, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(332, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(333, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(334, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(335, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(336, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(337, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(338, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(339, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(340, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(341, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(342, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(343, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(344, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(345, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(346, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(347, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(348, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(349, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(350, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(351, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(352, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(353, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(354, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(355, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(356, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(357, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(358, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(359, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(360, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(361, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(362, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(363, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(364, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(365, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(366, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(367, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(368, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(369, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(370, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(371, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(372, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(373, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(374, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(375, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(376, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(377, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(378, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(379, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(380, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(381, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(382, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(383, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(384, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(385, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(386, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(387, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(388, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(389, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(390, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(391, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(392, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(393, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(394, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(395, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(396, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(397, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(398, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(399, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(400, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(401, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(402, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(403, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(404, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(405, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(406, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(407, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(408, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(409, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(410, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(411, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(412, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(413, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(414, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(415, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(416, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(417, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(418, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(419, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(420, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(421, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(422, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(423, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(424, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(425, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(426, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(427, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(428, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(429, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(430, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(431, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(432, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(433, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(434, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(435, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(436, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(437, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(438, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(439, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(440, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(441, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(442, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(443, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(444, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(445, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(446, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(447, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(448, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(449, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(450, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(451, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(452, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(453, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(454, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(455, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(456, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(457, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(458, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(459, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(460, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(461, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(462, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(463, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(464, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(465, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(466, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(467, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(468, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(469, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(470, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(471, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(472, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(473, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(474, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(475, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(476, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(477, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(478, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(479, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(480, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(481, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(482, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(483, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(484, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(485, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(486, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(487, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(488, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(489, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(490, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(491, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(492, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(493, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(494, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(495, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(496, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(497, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(498, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(499, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(500, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(501, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(502, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(503, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(504, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(505, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(506, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(507, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(508, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(509, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(510, p, unsafeptr(&a)) },
	func(p, a unsafeptr) { i_x(511, p, unsafeptr(&a)) },
}
