name: Go1.23

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    name: Test Go1.23 for macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags=-checklinkname=0 -v .

    - name: Go Test
      run: go test -ldflags=-checklinkname=0 -race -v .

  linux:
    name: Test Go1.23 for Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags=-checklinkname=0 -v .

    - name: Go Test amd64
      run: go test -ldflags=-checklinkname=0 -race -v .

    - name: Go Test 386
      run: GOARCH=386 go test -ldflags=-checklinkname=0 -v .

  windows:
    name: Test Go1.23 for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -ldflags=-checklinkname=0 -v .

    - name: Go Test amd64
      run: go test -ldflags=-checklinkname=0 -race -v .

    - name: Go Test 386
      run: |
        set GOARCH=386 
        go test -ldflags=-checklinkname=0 -v .
